# Generated by Django 3.1.2 on 2020-10-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer2',
        ),
    ]
